# See https://github.com/probot/settings for more information.

repository:
  name: probequest
  description: Toolkit for Playing with Wi-Fi Probe Requests
  homepage: https://probequest.readthedocs.io/en/latest/
  topics: python, python3, scapy, wifi-security, sniffer, dot11, network-attacks, monitoring, security, wireless, wifi, toolkit
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    description: New bug
    color: ee0701
  - name: documentation
    color: 2d2de2
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: featue request
    color: 96f7c3
  - name: good first issue
    color: 7057ff
  - name: help wanted
    color: 33aa3f
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: regression
    description: Software regression
    color: ee0701
  - name: security
    description: Security issue
    color: ee0701
  - name: wontfix
    color: ffffff

branches:
  - name: master
    protection:
      required_pull_request_reviews:
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/travis-ci
      enforce_admins: true
      restrictions:
  - name: develop
    protection:
      required_pull_request_reviews:
      required_status_checks:
      enforce_admins: false
      restrictions:
